# Ensure flatpak is configured

---

- name: Ensure flatpak repository remotes are configured
  community.general.flatpak_remote:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    flatpakrepo_url: '{{ item.url }}'
    method: '{{ item.method | default("system") }}'
  loop: '{{ fedora_workstation_flatpak_remotes }}'

- name: Ensure flatpak packages are installed
  community.general.flatpak:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ fedora_workstation_flatpak_packages }}'

